name: Weavus
description: Shared events 3.0
full_description: 'The social app that gives you back your time and social life.
<br>
<br>- Plan events with your friends, family or community.
<br>- Plan centrally (birthday, wedding...) or collaboratively (weekend, vacation).
<br>- Manage expenses, share high quality photos and videos.
<br>
<br>Coming soon.'
android: https://play.google.com/store/apps/details?id=com.weavus
iOS: https://testflight.apple.com/join/yoxlxirG
web: false
screenshots: false
#  - 1.png
#  - 2.png
#  - 3.png
#  - 4.png
#producthunt: https://telegra.ph/Replace-this-link-07-23
companies: false
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
